### ISSUE TITLE
Array identifier at the wrong place.

### ISSUE THREAD

**Issue by gwenvis** [SilvanDomino/GD2-Hangman#3]
Hello, I notice**d a MAJ**OR issue _in the code. In the comments, there's a particular example that stands out. Namely, the array identifier is_ in the **wrong place. This w_**ould be OK in other languages like C#, Java, or idk. But it's not in this case! Put it** after the variable n**_ame, and then it will compile if uncommented. thank you

https://github.com/SilvanDomino/GD2-Hangman/blob/6a355148c416277c2a04d25f754217923e20f1ae/Hangman.h#L32

**Comment by SilvanDomino** [comment]
Fixed this codebreaking issue.
